#!/usr/bin/env bash
#install nginx

apt-get update
apt-get -y install nginx
service nginx start
sed -i "37i location /redirect_me {\
return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
}"  /etc/nginx/sites-available/default
nginx -t && service nginx restart
