#!/usr/bin/env bash
#install nginx

apt-get update
apt-get -y install nginx
service nginx start
sed -i "37i  error_page 404 /custom_404.html;\
location /custom_404.html {\
root /usr/share/nginx/html;\
internal;\
}"  /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
nginx -t && service nginx restart
