#!/usr/bin/env bash
#install nginx with header 
# shellcheck disable=SC2154
#shellcheck disable=SC2016
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i '15i \\tadd_header X-Served-By $HOSTNAME;' /etc/nginx/nginx.conf
sudo service nginx restart
