#!/usr/bin/env bash
# runs mutiple commands thru trap

echo $$ > /var/run/holbertonscript.pid
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/holbertonscript.pid; kill -9 $$' SIGTERM SIGQUIT

while true; do
	echo "To infinity and beyond"
	sleep 2
done
