#!/usr/bin/env bash
# infinite process with start,stop,restart cmds

function manage_my_process{
	while true; do
		echo "I am alive!" > /tmp/my_process
		sleep 2
	done
}

for arg
do
	case arg in
		start)
			echo $$ > /var/run/my_process.pid
			echo "manage_my_process started"
			;;
		stop)
			rm /var/run/my_process.pid
			echo "manage_my_process stopped"
			;;
		restart)
			rm /var/run/my_process.pid
			echo "manage_my_process restarted"
