#!/usr/bin/env bash
# FIZZBUZZ in BASH
 x=1
 while (( x <= 100 ))
 do
	 if (( x % 15 == 0 ));then 
		echo "FizzBuzz"
        elif (( x % 5 == 0 )); then
		 echo "Buzz"
        elif (( x % 3 == 0 )); then
		 echo "Fizz"
        else
                echo "$x"
        fi
	let x+=1 
done
