#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times 
 COUNTER=20
         until [  $COUNTER -lt 11 ]; do
             echo "Holberton School"
             let COUNTER-=1 
         done
