#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times 
 COUNTER=0
 while (( COUNTER < 10 ))
 do
	 echo "Holberton School"
	 let COUNTER=COUNTER+1 
	 if ((COUNTER == 9));then
		 echo "Hi"
	 fi
done
