#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times 
 COUNTER=0
 while (( COUNTER < 10 ))
 do
	 if ((COUNTER == 3));then
		 echo "bad luck"
	 elif ((COUNTER == 7));then
		 echo "good luck"
	else
	 echo "Holberton School"
	 fi
	 let COUNTER+=1 
done
