#!/usr/bin/env bash
# set default user to nginx and listen to port 8080
pkill apache2
sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
